sudo: false
language: node_js
install:
  - pip install --user awscli
node_js:
  - "12"
env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

jobs:
  include:
    - name: Short tests
      script: make -j2 short-tests
    - name: Long tests
      script: make -j2 long-tests
    - name: Lint
      script: make -j2 lint
    - stage: deploy
      if: branch = master and type != pull_request
      env: TEST_SUITE=upload
    - stage: deploy
      name: Electron Windows & Mac
      os: osx
      osx_image: xcode10.1
      script:
        - npm install
        - npm run dist -- --mac --win
    - stage: deploy
      name: Linux
      os: linux
      dist: trusty
      script:
        - npm install
        - npm run dist
